In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
x = Series([1,2,3,4])

In [3]:
x

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
x.values

array([1, 2, 3, 4], dtype=int64)

In [5]:
x.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
cas = Series([65,57,43,45],index = ['ram','shyam','gita','sita'])

In [7]:
cas

ram      65
shyam    57
gita     43
sita     45
dtype: int64

In [10]:
cas.index

Index([u'ram', u'shyam', u'gita', u'sita'], dtype='object')

In [11]:
cas.values

array([65, 57, 43, 45], dtype=int64)

In [12]:
cas['gita']

43

In [13]:
cas[cas > 45]

ram      65
shyam    57
dtype: int64

In [14]:
dct = cas.to_dict()

In [15]:
dct

{'gita': 43, 'ram': 65, 'shyam': 57, 'sita': 45}

In [16]:
ser1 = Series(dct)

In [18]:
ser1

gita     43
ram      65
shyam    57
sita     45
dtype: int64

In [19]:
ser1.notnull()

gita     True
ram      True
shyam    True
sita     True
dtype: bool

In [20]:
ser1.isnull()

gita     False
ram      False
shyam    False
sita     False
dtype: bool

In [21]:
ser1.index.name = 'age of people'

In [22]:
ser1

age of people
gita     43
ram      65
shyam    57
sita     45
dtype: int64

In [26]:
import webbrowser
website = 'https://en.wikipedia.org/wiki/NFL_win-loss_records'
webbrowser.open(website)

True

In [28]:
nfl_dataframe = pd.read_clipboard()

In [29]:
nfl_dataframe

Rank     Team       Won      Lost  Tied  Pct.   First       NFL Season  \
0     1  Chicago     Bears       741   555    42   0.570  1920.000  1,338   
1     2   Dallas   Cowboys       480   364     6   0.568  1960.000    850   
2     3    Green       Bay   Packers   720   547  37.000     0.566   1921   
3     4    Miami  Dolphins       429   335     4   0.561  1966.000    768   
4     5      New   England  Patriots   462   381   9.000     0.548   1960   

   Total  Games Division  
0    NFC  North      NaN  
1    NFC   East      NaN  
2  1,304    NFC    North  
3    AFC   East      NaN  
4    852    AFC     East

In [32]:
nfl_dataframe.columns

Index([u'Rank', u'Team', u'Won', u'Lost', u'Tied', u'Pct.', u'First', u'NFL',
       u'Season', u'Total', u'Games', u'Division'],
      dtype='object')

In [37]:
DataFrame(nfl_dataframe, columns = ['NFL','Season','Stadium'])

NFL Season  Stadium
0  1920.000  1,338      NaN
1  1960.000    850      NaN
2     0.566   1921      NaN
3  1966.000    768      NaN
4     0.548   1960      NaN

In [39]:
nfl_dataframe.ix[4]

Rank               5
Team             New
Won          England
Lost        Patriots
Tied             462
Pct.             381
First              9
NFL            0.548
Season          1960
Total            852
Games            AFC
Division        East
Name: 4, dtype: object

In [40]:
Stadiums = Series(['xyz','pqr'],index=[3,0])

In [41]:
Stadiums

3    xyz
0    pqr
dtype: object

In [42]:
nfl_dataframe['Stadium'] = Stadiums

In [43]:
nfl_dataframe

Rank     Team       Won      Lost  Tied  Pct.   First       NFL Season  \
0     1  Chicago     Bears       741   555    42   0.570  1920.000  1,338   
1     2   Dallas   Cowboys       480   364     6   0.568  1960.000    850   
2     3    Green       Bay   Packers   720   547  37.000     0.566   1921   
3     4    Miami  Dolphins       429   335     4   0.561  1966.000    768   
4     5      New   England  Patriots   462   381   9.000     0.548   1960   

   Total  Games Division Stadium  
0    NFC  North      NaN     pqr  
1    NFC   East      NaN     NaN  
2  1,304    NFC    North     NaN  
3    AFC   East      NaN     xyz  
4    852    AFC     East     NaN

In [44]:
del nfl_dataframe['Stadium']

In [45]:
nfl_dataframe

Rank     Team       Won      Lost  Tied  Pct.   First       NFL Season  \
0     1  Chicago     Bears       741   555    42   0.570  1920.000  1,338   
1     2   Dallas   Cowboys       480   364     6   0.568  1960.000    850   
2     3    Green       Bay   Packers   720   547  37.000     0.566   1921   
3     4    Miami  Dolphins       429   335     4   0.561  1966.000    768   
4     5      New   England  Patriots   462   381   9.000     0.548   1960   

   Total  Games Division  
0    NFC  North      NaN  
1    NFC   East      NaN  
2  1,304    NFC    North  
3    AFC   East      NaN  
4    852    AFC     East

In [46]:
dct = {'Name' :['Jyoti','Bhakti','Sam'],'age':[40,32,28]}

In [47]:
dct

{'Name': ['Jyoti', 'Bhakti', 'Sam'], 'age': [40, 32, 28]}

In [48]:
new_df = DataFrame(dct)

In [49]:
new_df

Name  age
0   Jyoti   40
1  Bhakti   32
2     Sam   28

In [50]:
website = 'http://pandas.pydata.org/pandas-doc/dev/generated/pandas.DataFrame.html'
webbrowser.open(website)

True

## Index objects

In [51]:
ser1 = Series([1,2,3,4],index=['a','b','c','d'])

In [52]:
ser1

a    1
b    2
c    3
d    4
dtype: int64

In [53]:
ind1 = ser1.index

In [54]:
ind1

Index([u'a', u'b', u'c', u'd'], dtype='object')

In [55]:
ind1[2]

'c'

In [56]:
from numpy.random import randn

In [59]:
ser2 = ser1.reindex(['fsdf','sffdsf','fsdfsd','gfgdfg'],fill_value = 0)

In [60]:
ser2

fsdf      0
sffdsf    0
fsdfsd    0
gfgdfg    0
dtype: int64

In [63]:
del ser2

In [65]:
ser2 = Series(['abc','efg','ijk','pqr'],index = [1,6,8,10])

In [66]:
ser2

1     abc
6     efg
8     ijk
10    pqr
dtype: object

In [67]:
xyz = np.arange(11)

In [68]:
xyz

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
ser2.reindex(xyz,method='ffill')

0     NaN
1     abc
2     abc
3     abc
4     abc
5     abc
6     efg
7     efg
8     ijk
9     ijk
10    pqr
dtype: object

## Drop

In [74]:
ser2.drop(8)

1     abc
6     efg
10    pqr
dtype: object

In [75]:
ser2

1     abc
6     efg
8     ijk
10    pqr
dtype: object

In [8]:
dframe = DataFrame(np.arange(12).reshape(3,4),index = ['a','b','c'],columns = ['col1','col2','col3','col4'])

In [9]:
dframe

col1  col2  col3  col4
a     0     1     2     3
b     4     5     6     7
c     8     9    10    11

In [11]:
dframe.drop('c', axis = 0)

col1  col2  col3  col4
a     0     1     2     3
b     4     5     6     7

In [79]:
dframe.drop('b')

col1  col2  col3  col4
a     0     1     2     3
c     8     9    10    11

## Selection

In [80]:
dframe

col1  col2  col3  col4
a     0     1     2     3
b     4     5     6     7
c     8     9    10    11

In [82]:
dframe.ix[1]

col1    4
col2    5
col3    6
col4    7
Name: b, dtype: int32

In [85]:
ser3 = Series([0,1,2],index = ['a','b','c'])
ser4 = Series([3,4,5,6],index = ['a','b','c','d'])

In [86]:
ser3 + ser4

a     3
b     5
c     7
d   NaN
dtype: float64

In [87]:
ser3.order()

a    0
b    1
c    2
dtype: int64

In [88]:
ser3.sort_index()

a    0
b    1
c    2
dtype: int64

In [89]:
ser3.sort()

In [90]:
ser3

a    0
b    1
c    2
dtype: int64

In [91]:
ser3.rank()

a    1
b    2
c    3
dtype: float64

In [5]:
df1 = pd.date_range('2014-01-01','2015-01-01')

In [6]:
df1


DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06', '2014-01-07', '2014-01-08',
               '2014-01-09', '2014-01-10', 
               ...
               '2014-12-23', '2014-12-24', '2014-12-25', '2014-12-26',
               '2014-12-27', '2014-12-28', '2014-12-29', '2014-12-30',
               '2014-12-31', '2015-01-01'],
              dtype='datetime64[ns]', length=366, freq='D', tz=None)

In [7]:
date = df1
del df1

In [8]:
df1


NameError: name 'df1' is not defined

In [9]:
date

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06', '2014-01-07', '2014-01-08',
               '2014-01-09', '2014-01-10', 
               ...
               '2014-12-23', '2014-12-24', '2014-12-25', '2014-12-26',
               '2014-12-27', '2014-12-28', '2014-12-29', '2014-12-30',
               '2014-12-31', '2015-01-01'],
              dtype='datetime64[ns]', length=366, freq='D', tz=None)

In [10]:
df1 = pd.DataFrame(index=date)

In [11]:
df1

Empty DataFrame
Columns: []
Index: [2014-01-01 00:00:00, 2014-01-02 00:00:00, 2014-01-03 00:00:00, 2014-01-04 00:00:00, 2014-01-05 00:00:00, 2014-01-06 00:00:00, 2014-01-07 00:00:00, 2014-01-08 00:00:00, 2014-01-09 00:00:00, 2014-01-10 00:00:00, 2014-01-11 00:00:00, 2014-01-12 00:00:00, 2014-01-13 00:00:00, 2014-01-14 00:00:00, 2014-01-15 00:00:00, 2014-01-16 00:00:00, 2014-01-17 00:00:00, 2014-01-18 00:00:00, 2014-01-19 00:00:00, 2014-01-20 00:00:00, 2014-01-21 00:00:00, 2014-01-22 00:00:00, 2014-01-23 00:00:00, 2014-01-24 00:00:00, 2014-01-25 00:00:00, 2014-01-26 00:00:00, 2014-01-27 00:00:00, 2014-01-28 00:00:00, 2014-01-29 00:00:00, 2014-01-30 00:00:00, 2014-01-31 00:00:00, 2014-02-01 00:00:00, 2014-02-02 00:00:00, 2014-02-03 00:00:00, 2014-02-04 00:00:00, 2014-02-05 00:00:00, 2014-02-06 00:00:00, 2014-02-07 00:00:00, 2014-02-08 00:00:00, 2014-02-09 00:00:00, 2014-02-10 00:00:00, 2014-02-11 00:00:00, 2014-02-12 00:00:00, 2014-02-13 00:00:00, 2014-02-14 00:00:00, 2014-02-15 00:00:00, 2014-02-16 00:00:00, 2014-02-17 00:00:00, 2014-02-18 00:00:00, 2014-02-19 00:00:00, 2014-02-20 00:00:00, 2014-02-21 00:00:00, 2014-02-22 00:00:00, 2014-02-23 00:00:00, 2014-02-24 00:00:00, 2014-02-25 00:00:00, 2014-02-26 00:00:00, 2014-02-27 00:00:00, 2014-02-28 00:00:00, 2014-03-01 00:00:00, 2014-03-02 00:00:00, 2014-03-03 00:00:00, 2014-03-04 00:00:00, 2014-03-05 00:00:00, 2014-03-06 00:00:00, 2014-03-07 00:00:00, 2014-03-08 00:00:00, 2014-03-09 00:00:00, 2014-03-10 00:00:00, 2014-03-11 00:00:00, 2014-03-12 00:00:00, 2014-03-13 00:00:00, 2014-03-14 00:00:00, 2014-03-15 00:00:00, 2014-03-16 00:00:00, 2014-03-17 00:00:00, 2014-03-18 00:00:00, 2014-03-19 00:00:00, 2014-03-20 00:00:00, 2014-03-21 00:00:00, 2014-03-22 00:00:00, 2014-03-23 00:00:00, 2014-03-24 00:00:00, 2014-03-25 00:00:00, 2014-03-26 00:00:00, 2014-03-27 00:00:00, 2014-03-28 00:00:00, 2014-03-29 00:00:00, 2014-03-30 00:00:00, 2014-03-31 00:00:00, 2014-04-01 00:00:00, 2014-04-02 00:00:00, 2014-04-03 00:00:00, 2014-04-04 00:00:00, 2014-04-05 00:00:00, 2014-04-06 00:00:00, 2014-04-07 00:00:00, 2014-04-08 00:00:00, 2014-04-09 00:00:00, 2014-04-10 00:00:00, ...]

[366 rows x 0 columns]